//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_parqueo
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int id_customer { get; set; }
        public string customer_name { get; set; }
        public string customer_lastname { get; set; }
        public string customer_DUI { get; set; }
        public string customer_password { get; set; }
    }
}
