//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_parqueo
{
    using System;
    using System.Collections.Generic;
    
    public partial class parking_slot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public parking_slot()
        {
            this.parking_slot_reservation = new HashSet<parking_slot_reservation>();
        }
    
        public int id_parking_slot { get; set; }
        public int id_parking_lot { get; set; }
        public int slot_number { get; set; }
        public string is_parking_slot_free { get; set; }
    
        public virtual parking_lot parking_lot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parking_slot_reservation> parking_slot_reservation { get; set; }
    }
}
