//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_parqueo
{
    using System;
    using System.Collections.Generic;
    
    public partial class parking_slot_reservation
    {
        public int id_reservation { get; set; }
        public string customer_DUI { get; set; }
        public int id_parking_slot { get; set; }
        public System.DateTime hora_reserva { get; set; }
        public int duration_in_minutes { get; set; }
        public System.DateTime hora_finalizada { get; set; }
    
        public virtual parking_slot parking_slot { get; set; }
    }
}
